//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecResults.WebApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpecResults.WebApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] glyphicons_halflings_regular_eot {
            get {
                object obj = ResourceManager.GetObject("glyphicons_halflings_regular_eot", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] glyphicons_halflings_regular_svg {
            get {
                object obj = ResourceManager.GetObject("glyphicons_halflings_regular_svg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] glyphicons_halflings_regular_ttf {
            get {
                object obj = ResourceManager.GetObject("glyphicons_halflings_regular_ttf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] glyphicons_halflings_regular_woff {
            get {
                object obj = ResourceManager.GetObject("glyphicons_halflings_regular_woff", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html ng-app=&quot;app&quot;&gt;
        ///
        ///&lt;head&gt;
        ///	&lt;title&gt;__TITLE__&lt;/title&gt;
        ///	&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///	&lt;link href=&quot;css/styles.css?v=__VERSION__&quot; rel=&quot;stylesheet&quot;&gt;
        ///	&lt;style type=&quot;text/css&quot;&gt;
        ///	 __CSS__
        ///	&lt;/style&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body ng-view&gt;
        ///
        ///	&lt;script src=&quot;js/scripts.js?v=__VERSION__&quot;&gt;&lt;/script&gt;
        ///	&lt;script src=&quot;js/report.js?v=__VERSION__&quot;&gt;&lt;/script&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string index_html {
            get {
                return ResourceManager.GetString("index_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * SpecResults.WebApp v0.0.0 by Tim Schlechter
        /// * 
        /// */
        ///
        ///!function(a,b){&quot;object&quot;==typeof module&amp;&amp;&quot;object&quot;==typeof module.exports?module.exports=a.document?b(a,!0):function(a){if(!a.document)throw new Error(&quot;jQuery requires a window with a document&quot;);return b(a)}:b(a)}(&quot;undefined&quot;!=typeof window?window:this,function(a,b){function c(a){var b=a.length,c=_.type(a);return&quot;function&quot;===c||_.isWindow(a)?!1:1===a.nodeType&amp;&amp;b?!0:&quot;array&quot;===c||0===b||&quot;number&quot;==typeof b&amp;&amp;b&gt;0&amp;&amp;b-1 in a}function d(a,b,c){if(_.isF [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string scripts_min_js {
            get {
                return ResourceManager.GetString("scripts_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;version&quot;:3,&quot;file&quot;:&quot;scripts.min.js&quot;,&quot;sources&quot;:[&quot;..\\..\\bower_components\\jquery\\dist\\jquery.js&quot;,&quot;..\\..\\bower_components\\lodash\\dist\\lodash.js&quot;,&quot;..\\..\\bower_components\\angular\\angular.js&quot;,&quot;..\\..\\bower_components\\angular-route\\angular-route.js&quot;,&quot;..\\..\\bower_components\\uri.js\\src\\URI.js&quot;,&quot;..\\..\\bower_components\\bootstrap\\js\\collapse.js&quot;,&quot;..\\..\\bower_components\\bootstrap\\js\\dropdown.js&quot;,&quot;..\\..\\bower_components\\angular-ui-bootstrap-bower\\ui-bootstrap-tpls.js&quot;,&quot;..\\..\\src\\app [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string scripts_min_map {
            get {
                return ResourceManager.GetString("scripts_min_map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! normalize.css v3.0.0 | MIT License | git.io/normalize */html{font-family:sans-serif;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%}body{margin:0}article,aside,details,figcaption,figure,footer,header,hgroup,main,nav,section,summary{display:block}audio,canvas,progress,video{display:inline-block;vertical-align:baseline}audio:not([controls]){display:none;height:0}[hidden],template{display:none}a{background:transparent}a:active,a:hover{outline:0}abbr[title]{border-bottom:1px dotted}b,strong{font-wei [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string styles_min_css {
            get {
                return ResourceManager.GetString("styles_min_css", resourceCulture);
            }
        }
    }
}
